---

- hosts: zorinnodes
  become: true
  tasks:

  - name: Install python-psutil package
    apt: name=python-psutil

  - name: copy wallpaper file
    copy:
      src: /home/jrbanua/ansible/files/wallpaper.jpg
      dest: /home/itops/Pictures/wallpaper.jpg
      owner: root
      group: root
 
  - name: set wallpaper
    become_user: itops
    dconf:
      key="/org/gnome/desktop/background/picture-uri"
      value= "'file:///home/itops/Pictures/wallpaper.jpg'"

  - name: set wallpaper position
    become_user: itops
    dconf:
      key="/org/gnome/desktop/background/picture-options"
      value="'zoom'"
