---

- hosts: zorinnodes
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - vim-nox 

  - name: Install python3-psutil package
    apt: name=python3-psutil

  - name: copy wallpaper file
    copy:
      src: /home/jrbanua/ansible/files/wallpaper_test.jpg
      dest: /usr/share/backgrounds/linuxtest.jpg
      owner: root
      group: root
 
  - name: set wallpaper
    shell:
        "dconf write /org/gnome/desktop/background/picture-uri "'file:///usr/share/backgrounds/Wonders_Wallpaper.png'""
