---

- hosts: zorinnodes
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - vim-nox
 
  - name: unlock background
    become_user: itops
    shell: |
         sudo rm /etc/dconf/db/local.d/00-background
         sudo rm /etc/dconf/db/local.d/locks/background
         sudo dconf update 

  - name: copy wallpaper file
    copy:
      src: /home/jrbanua/ansible/files/wallpaper_test.jpg
      dest: /usr/share/backgrounds/linuxtest.jpg
      owner: root
      group: root

  - name: copy script file
    copy:
      src: /home/jrbanua/ansible/files/change-background.sh
      dest: /home/wonders/Documents/change-background.sh
 
  - name: set wallpaper
    become_user: wonders
    command: sh /home/wonders/Documents/change-background.sh
