---
- name: Copy and install Google Chrome on Linux
  hosts: troubleshooting
  become: true
  tasks:
    - name: Copy Google Chrome installer to the target machine
      copy:
        src: /path/to/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb
        mode: '0644'

    - name: Install Google Chrome on Debian-based systems
      apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb

    - name: Verify Google Chrome installation
      command: google-chrome --version
      register: chrome_version_output
      ignore_errors: true

    - name: Display installed Google Chrome version
      debug:
        msg: "Installed Google Chrome version: {{ chrome_version_output.stdout }}"
