---
- name: Send pop-up reminder
  hosts: troubleshooting
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure libnotify is installed   
      ansible.builtin.package:
        name: libnotify-bin
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Send pop-up notification
      ansible.builtin.command:
        cmd: 'zenity --info --width=300 --height=100 --text="THIS IS FROM IT. PLEASE SWITCH TO PH-API AND CLEAR CACHE IF YOU CONTINUE NOT TO RECEIVE CALLS"'
  environment:
    DISPLAY: ":0"
  become_user: wonders