---
- name: Send pop-up reminder
  hosts: BAY_N
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure libnotify is installed   
      ansible.builtin.package:
        name: libnotify-bin
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Send pop-up notification
      ansible.builtin.command:
        cmd: 'zenity --info --width=300 --height=100 --text="WARNING! YOUR INTERNET USAGE IS BEING MONITORED. PLEASE REFRAIN FROM ACCESSING UNWANTED SITES. CONTINUED ACCESS ON THESE SITES MAY LEAD TO DISCIPLINARY ACTION!"'
  environment:
    DISPLAY: ":0"
  become_user: wonders